use batiskaf::SqlDelete;
use batiskaf_derive::*;

#[test]
fn test_simple_key() {
    #[allow(unused)]
    #[derive(SqlDelete)]
    struct Person {
        #[batiskaf(primary_key, autogenerated)]
        id: i64,
        name: String,
        age: Option<u32>,
    };
    let sql = Person::delete_statement("person");
    assert_eq!("DELETE FROM person WHERE id = :id", sql);
}

#[test]
fn test_complex_key() {
    #[allow(unused)]
    #[derive(SqlDelete)]
    struct FieldValue {
        #[batiskaf(primary_key)]
        x: i64,
        #[batiskaf(primary_key)]
        y: i64,
        value: f64,
    };
    let sql = FieldValue::delete_statement("height");
    assert_eq!("DELETE FROM height WHERE x = :x AND y = :y", sql);
}
