use batiskaf::SqlUpdate;
use batiskaf_derive::*;

#[test]
fn test_simple_key() {
    #[allow(unused)]
    #[derive(SqlUpdate)]
    struct Person {
        #[batiskaf(primary_key, autogenerated)]
        id: i64,
        name: String,
        age: Option<u32>,
    }
    let sql = Person::update_statement("person");
    assert_eq!(
        "UPDATE person SET name = :name, age = :age WHERE id = :id",
        sql
    );
}

#[test]
fn test_complex_key() {
    #[allow(unused)]
    #[derive(SqlUpdate)]
    struct FieldValue {
        #[batiskaf(primary_key)]
        x: i64,
        #[batiskaf(primary_key)]
        y: i64,
        value: f64,
    }
    let sql = FieldValue::update_statement("height");
    assert_eq!(
        "UPDATE height SET value = :value WHERE x = :x AND y = :y",
        sql
    );
}
